def bishops(bishop):
    bishop.penup()
    bishop.forward(20)
    bishop.left(90)
    bishop.forward(4)
    bishop.right(90)
    bishop.pendown()
    bishop.pencolor("black")
    bishop.begin_fill()

    bishop.forward(34)
    bishop.left(90)
    bishop.forward(10)
    bishop.left(60)
    bishop.forward(12)
    bishop.right(110)
    bishop.circle(28,108)
    bishop.penup()
    bishop.circle(28,12)
    bishop.pendown()
    bishop.left(110)
    bishop.penup()
    bishop.forward(8)
    bishop.pendown()
    bishop.left(90)
    bishop.circle(7.5,360)
    bishop.left(90)
    bishop.penup()
    bishop.forward(8)
    bishop.pendown()
    bishop.left(110)

    bishop.penup()
    bishop.circle(28,15)
    bishop.pendown()

    bishop.circle(28,10)
    bishop.left(40)
    bishop.circle(28,70)
    bishop.left(200)
    bishop.circle(-28,60)
    bishop.left(140)
    bishop.circle(28,70)
    bishop.right(110)
    bishop.forward(12)
    bishop.left(55)
    bishop.forward(8)
    bishop.end_fill()


    