def kings(king):
    king.penup()
    king.forward(20)
    king.left(90)
    king.forward(4)
    king.right(90)
    king.pendown()
    king.pencolor("black")
    king.begin_fill()

    king.forward(43)
    king.left(90)
    king.forward(10)
    king.left(50)
    king.forward(7)
    king.right(50)
    king.circle(-50, 35)
    king.left(95)
    king.circle(50, 27.5)
    king.right(85)
    king.forward(7)
    king.right(90)
    king.forward(10)
    king.left(90)
    king.forward(6)
    king.left(90)
    king.forward(10)
    king.right(95)
    king.forward(7)
    king.left(95)
    king.forward(7)
    king.left(90)
    king.forward(6)
    king.right(90)
    king.forward(10)
    king.left(90)
    king.forward(6)
    king.left(90)
    king.forward(10)
    king.right(90)
    king.forward(7)
    king.right(85)
    king.circle(50, 27.5)
    king.left(90)
    king.circle(-50, 35)
    king.right(50)
    king.forward(7)
    king.left(50)
    king.forward(10)
    king.end_fill()