def knights(knight):
    knight.penup()
    knight.forward(20)
    knight.left(90)
    knight.forward(4)
    knight.right(90)
    knight.pendown()
    knight.pencolor("black")
    knight.begin_fill()

    knight.forward(39)
    knight.left(90)
    knight.forward(10)
    knight.left(50)
    knight.forward(5)
    knight.right(80)
    knight.circle(45,20)
    knight.left(8.5)
    knight.circle(45,20)
    knight.left(8.5)
    knight.circle(45,30)
    knight.right(23.5)
    knight.forward(12)
    knight.left(130)
    knight.circle(45,15)
    knight.right(35)
    knight.forward(12)
    knight.left(25)
    knight.forward(5)
    knight.right(25)
    knight.forward(17)
    knight.left(100)
    knight.forward(10)
    knight.left(80)
    knight.forward(7)
    knight.right(35)
    knight.circle(20,35)
    knight.right(150)
    knight.circle(-20,40)
    knight.circle(20,40)
    knight.right(50)
    knight.forward(8)
    knight.left(55)
    knight.forward(10)
    knight.end_fill()





