def pawns(pawn):
    """
    Draws a pawn chess piece.
    Receives a turtle object 'pawn' to draw the piece.
    """
    pawn.penup()
    pawn.forward(20)
    pawn.left(90)
    pawn.forward(4)
    pawn.right(90)
    pawn.pendown()
    pawn.pencolor("black")
    pawn.begin_fill()
    pawn.forward(40)
    pawn.left(90)
    pawn.forward(7.5)
    pawn.left(50)
    pawn.forward(20)
    pawn.right(50)
    pawn.forward(13)
    pawn.left(90)
    pawn.penup()
    pawn.forward(5)
    pawn.pendown()
    pawn.left(180)

    pawn.penup()
    pawn.circle(15,20)
    pawn.pendown()

    pawn.circle(15,325)
    pawn.penup()
    pawn.circle(15,15)
    pawn.pendown()
    pawn.left(180)
    pawn.penup()
    pawn.forward(5)
    pawn.pendown()
    pawn.left(90)
    pawn.forward(13)
    pawn.right(50)
    pawn.forward(20)
    pawn.left(50)
    pawn.forward(7.5)
    pawn.end_fill()