def queens(queen):
    queen.penup()
    queen.forward(20)
    queen.left(90)
    queen.forward(4)
    queen.right(90)
    queen.pendown()
    queen.pencolor("black")
    queen.begin_fill()

    queen.forward(40)
    queen.left(90)
    queen.forward(10)
    queen.left(50)
    queen.forward(10)
    queen.right(70)
    queen.forward(35)
    queen.right(100)
    queen.circle(5, 360)
    queen.right(100)
    queen.forward(25)
    queen.right(140)
    queen.forward(30)
    queen.right(100)
    queen.circle(5, 360)
    queen.right(100)
    queen.forward(25)
    queen.right(140)
    queen.forward(25)
    queen.right(80)
    queen.circle(5, 360)
    queen.right(120)
    queen.forward(30)
    queen.right(140)
    queen.forward(24)
    queen.right(100)
    queen.circle(5, 360)
    queen.right(100)
    queen.forward(35)
    queen.right(70)
    queen.forward(10)
    queen.left(50)
    queen.forward(10)
    queen.end_fill()
    
